name: flutter_sample
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk : flutter

  rect_getter: ^1.0.0
  desktop_multi_window: ^0.0.1
  # linear_progress_loading:
  #   path: ../linear_progress_loading

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
